apiVersion: v1
kind: ConfigMap
metadata:
  name: protocol-config
  namespace: beckn-onix
data:
  bap-client.yml: |
    server:
      port: ${BAP_CLIENT_PORT}
    cache:
      host: "${REDIS_URL}"
      port: 6379
      ttl: "PT10M"
      db: 1
    responseCache:
      mongoURL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}/${MONGO_DB_NAME}?authSource=admin"
      ttl: "PT10M"
    client:
      synchronous: 
        mongoURL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}/${MONGO_DB_NAME}?authSource=admin"
    app:
      mode: bap
      gateway:
        mode: client
        inboxQueue: "inbox"
        outboxQueue: "outbox"
        amqpURL: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_URL}:5672"
      actions:
        requests:
          search:
            ttl: "PT15S"
          # ... other actions
        responses: 
          on_search:
            ttl: "PT15S"
          # ... other responses
      privateKey: "PRIVATE_KEY"
      publicKey: "PUBLIC_KEY"
      subscriberId: "${BAP_SUBSCRIBER_ID}"
      subscriberUri: "${BAP_SUBSCRIBER_URL}"
      registryUrl: "${REGISTRY_URL}"
      auth: false
      uniqueKey: "${BAP_SUBSCRIBER_KEY_ID}"
      city: "std:080"
      country: "IND"
      ttl: "PT10M"
      httpTimeout: "PT3S"
      httpRetryCount: 2
      telemetry:
        enabled: false
      useLayer2Config: ${USE_LAYER_2_CONFIG}
      mandateLayer2Config: ${MANDATE_LAYER_2_CONFIG}

  bap-network.yml: |
    server:
      port: ${BAP_NETWORK_PORT}
    cache:
      host: "${REDIS_URL}"
      port: 6379
      ttl: "PT10M"
      db: 1
    responseCache:
      mongoURL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}/${MONGO_DB_NAME}?authSource=admin"
      ttl: "PT10M"
    client:
      synchronous: 
        mongoURL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}/${MONGO_DB_NAME}?authSource=admin"
    app:
      mode: bap
      gateway:
        mode: network
        inboxQueue: "inbox"
        outboxQueue: "outbox"
        amqpURL: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_URL}:5672"
      actions:
        requests:
          search:
            ttl: "PT15S"
          # ... other actions
        responses: 
          on_search:
            ttl: "PT15S"
          # ... other responses
      privateKey: "PRIVATE_KEY"
      publicKey: "PUBLIC_KEY"
      subscriberId: "${BAP_SUBSCRIBER_ID}"
      subscriberUri: "${BAP_SUBSCRIBER_URL}"
      registryUrl: "${REGISTRY_URL}"
      auth: false
      uniqueKey: "${BAP_SUBSCRIBER_KEY_ID}"
      city: "std:080"
      country: "IND"
      ttl: "PT10M"
      httpTimeout: "PT3S"
      httpRetryCount: 2
      telemetry:
        enabled: false
      useLayer2Config: ${USE_LAYER_2_CONFIG}
      mandateLayer2Config: ${MANDATE_LAYER_2_CONFIG}