apiVersion: v1
kind: ConfigMap
metadata:
  name: bpp-config
  namespace: beckn-onix
data:
  bpp-client.yml: |
    server:
      port: ${BPP_CLIENT_PORT}

    cache:
      host: "${REDIS_URL}"
      port: 6379
      ttl: "PT10M"
      db: 0

    responseCache:
      mongoURL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}/${MONGO_DB_NAME}?authSource=admin"
      ttl: "PT10M"

    client:
      webhook:
        url: "${WEBHOOK_URL}"

    app:
      mode: bpp
      gateway:
        mode: client
        inboxQueue: "inbox-bpp"
        outboxQueue: "outbox-bpp"
        amqpURL: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_URL}:5672"

      actions:
        requests:
          search:
            ttl: "PT15S"
        responses:
          on_search:
            ttl: "PT15S"

      privateKey: "PRIVATE_KEY"
      publicKey: "PUBLIC_KEY"
      subscriberId: "${BPP_SUBSCRIBER_ID}"
      subscriberUri: "${BPP_SUBSCRIBER_URL}"
      registryUrl: "${REGISTRY_URL}"
      auth: true
      uniqueKey: "${BPP_SUBSCRIBER_KEY_ID}"
      city: "std:080"
      country: "IND"
      ttl: "PT10M"
      httpTimeout: "PT3S"
      httpRetryCount: 2
      telemetry:
        enabled: false

      useLayer2Config: ${USE_LAYER_2_CONFIG}
      mandateLayer2Config: ${MANDATE_LAYER_2_CONFIG}

  bpp-network.yml: |
    server:
      port: ${BPP_NETWORK_PORT}

    cache:
      host: "${REDIS_URL}"
      port: 6379
      ttl: "PT10M"
      db: 0

    responseCache:
      mongoURL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@${MONGO_URL}/${MONGO_DB_NAME}?authSource=admin"
      ttl: "PT10M"

    client:
      webhook:
        url: "${WEBHOOK_URL}"

    app:
      mode: bpp
      gateway:
        mode: network
        inboxQueue: "inbox-bpp"
        outboxQueue: "outbox-bpp"
        amqpURL: "amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_URL}:5672"

      actions:
        requests:
          search:
            ttl: "PT15S"
        responses:
          on_search:
            ttl: "PT15S"

      privateKey: "PRIVATE_KEY"
      publicKey: "PUBLIC_KEY"
      subscriberId: "${BPP_SUBSCRIBER_ID}"
      subscriberUri: "${BPP_SUBSCRIBER_URL}"
      registryUrl: "${REGISTRY_URL}"
      auth: true
      uniqueKey: "${BPP_SUBSCRIBER_KEY_ID}"
      city: "std:080"
      country: "IND"
      ttl: "PT10M"
      httpTimeout: "PT3S"
      httpRetryCount: 2
      telemetry:
        enabled: false

      useLayer2Config: ${USE_LAYER_2_CONFIG}
      mandateLayer2Config: ${MANDATE_LAYER_2_CONFIG}
