routingRules:
  - domain: "retail:1.1.0"  # Retail domain
    version: "1.1.0"
    targetType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rating
      - support

  - domain: "retail:1.1.0"  # Retail domain
    version: "1.1.0"
    targetType: "url"
    target:
      url: "http://gateway:4030/bg"
    endpoints:
      - search

  - domain: "retail:1.1.0"  # Retail domain
    version: "1.1.0"
    targetType: "url"
    target:
      url: "https://34.93.141.21.sslip.io/beckn"
    endpoints:
      - discover
