appName: "networkSideReciever"
port: 9092
log:
  level: info
  destinations:
    - type: stdout
  context_keys:
    - requestId
    - userId
plugin:
  root: ../../shared/plugin/definition/
  publisher:
    id: publisher
    config:
      project: ondc-seller-dev
      topic: networkSideTopic
  validator:
    id: validatora
  encryption:
    id: encryption
    config:
      algorithm: RSA-OAEP
      key_id: test-key
