routingRules:
  - domain: "ONDC:TRV10"
    version: "2.0.0"
    routingType: "bpp"
    target:
      url: "https://gateway.example.com"
    endpoints:
      - search
  - domain: "ONDC:TRV10"
    version: "2.0.0"
    routingType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status
      - cancel
  - domain: "ONDC:TRV12"
    version: "2.0.0"
    routingType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status