routingRules:
  - domain: "ONDC:TRV10"
    version: "2.0.0"
    routingType: "url"
    target:
      url: "https://services-backend/trv/v1"
    endpoints:
      - select
      - init
      - confirm
      - status
      - cancel

  - domain: "ONDC:TRV10"
    version: "2.0.0"
    routingType: "msgq"
    target:
      topic_id: "trv_topic_id1"
    endpoints:
      - search

  - domain: "ONDC:TRV11"
    version: "2.0.0"
    routingType: "url"
    target:
      url: "https://services-backend/trv/v1"
    endpoints:
      - select
      - init
      - confirm