apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: beckn-onix
spec:
  selector:
    app: gateway
  ports:
  - name: http
    port: 4000
    targetPort: 4000
  - name: custom
    port: 4030
    targetPort: 4030
  type: ClusterIP