name: Build and Upload Plugins

on:
  push:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    env:
      PLUGIN_OUTPUT_DIR: ./generated
      ZIP_FILE: plugins_bundle.zip

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global url."https://${{ secrets.PAT_GITHUB }}:@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{ secrets.GERRIT_USERNAME }}:${{ secrets.GERRIT_PAT }}@open-networks.googlesource.com/".insteadOf "https://open-networks.googlesource.com/"

      - name: Clone GitHub and Gerrit plugin repos
        run: |
          # Example GitHub clone
          git clone -b beckn-onix-v1.0-develop https://github.com/beckn/beckn-onix.git github-repo
          
          # Example Gerrit clone
          git clone https://open-networks.googlesource.com/onix-dev gerrit-repo

      - name: List directory structure
        run: |
          echo "📂 Contents of root:"
          ls -alh
      
          echo "📂 Contents of GitHub repo:"
          ls -alh github-repo
      
          echo "📂 Deep list of GitHub repo:"
          find github-repo
      
          echo "📂 Contents of Gerrit repo:"
          ls -alh gerrit-repo
      
          echo "📂 Deep list of Gerrit repo:"
          find gerrit-repo
