name: Terraform Deploy to GCP

on:
  push:
  workflow_dispatch: # Manual trigger

jobs:
  plan:
    name: Terraform Plan Only
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repository
        uses: actions/checkout@v3

      - name: Clone Terraform repo from Gerrit
        run: |
          git clone https://${{ secrets.GERRIT_USERNAME }}:${{ secrets.GERRIT_PAT }}@open-networks.googlesource.com/onix-dev
          echo "==== Directory contents after clone ===="
          pwd
          ls -la
          echo "==== Contents of gerrit-repo ===="
          pwd
          ls -la gerrit-repo
          echo "==== Contents of Terraform-dir ===="
          pwd
          cd Terraform
          pwd
          la -la
